#!/usr/bin/env bash
# Script to install and configure HAproxy on a server

#Enable dedicated PPA
# apt-get -y install --no-install-recommends software-properties-common
# add-apt-repository -y ppa:vbernat/haproxy-2.0

# #Install with the following command 
# apt-get -y install haproxy

#configure HAproxy. File path is at 
# /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen load_balancing
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 420448-web-01 52.91.146.238:80 check
    server 420448-web-02 35.153.98.99 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start