#!/usr/bin/env bash
# Script to backup all databases in the mysql server

# Format time from variables using command substitution
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql