#!/usr/bin/env bash
# Indefinitely appends "I am alive" to the file /tmp/my_process and auses 2 seconds in between each message.   .

while :
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
