#!/usr/bin/env bash
# Replacing changing the ip within the host file

cp /etc/hosts ~/hosts.n
cat ~/hosts.n | sed -e 's/127.0.0.1/127.0.0.2/g' | ~/hosts.n
echo "8.8.8.8\tfacebook.com" >> ~/hosts.n
cp -f ~/hosts.n /etc/hosts